# Generated by Django 4.0.5 on 2022-06-16 08:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_voluntario', models.BooleanField(default=False, verbose_name='Voluntario')),
                ('is_adulto_mayor', models.BooleanField(default=False, verbose_name='Adulto Mayor')),
                ('phone_number', models.CharField(blank=True, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Ingrese un número de teléfono válido', regex='^[0-9]{10}$')], verbose_name='Número de teléfono')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdultoMayor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=255, verbose_name='Nombre(s)')),
                ('last_name', models.CharField(max_length=255, verbose_name='Apellidos')),
                ('location', models.CharField(max_length=255, verbose_name='Ubicación')),
            ],
        ),
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=255, verbose_name='Nombre(s)')),
                ('last_name', models.CharField(max_length=255, verbose_name='Apellidos')),
                ('location', models.CharField(max_length=255, verbose_name='Ubicación')),
                ('image', models.ImageField(upload_to='', verbose_name='Foto de perfil')),
                ('id_card', models.FileField(upload_to='', verbose_name='Identificación')),
            ],
        ),
    ]
