# Generated by Django 4.0.5 on 2022-06-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_voluntario_id_card_alter_voluntario_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntario',
            name='id_card',
            field=models.FileField(upload_to='media/voluntario/id/', verbose_name='Identificación'),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='image',
            field=models.ImageField(upload_to='media/voluntario/pfp/', verbose_name='Foto de perfil'),
        ),
    ]
